import unreal
L=unreal.MaterialEditingLibrary
mat=unreal.load_asset('/Game/Materials/M_GrassWind')
old=L.get_material_property_input_node(mat,unreal.MaterialProperty.MP_BASE_COLOR)
x,y=old.get_editor_property('material_expression_editor_x'),old.get_editor_property('material_expression_editor_y')
a=L.create_material_expression(mat,unreal.MaterialExpressionVectorParameter,x-400,y-150)
a.set_editor_property('parameter_name','GrassGreen'); a.set_editor_property('default_value',unreal.LinearColor(0.075,0.10,0.03,1))
b=L.create_material_expression(mat,unreal.MaterialExpressionVectorParameter,x-400,y+50)
b.set_editor_property('parameter_name','GrassDry'); b.set_editor_property('default_value',unreal.LinearColor(0.28,0.20,0.07,1))
r=L.create_material_expression(mat,unreal.MaterialExpressionPerInstanceRandom,x-400,y+250)
lp=L.create_material_expression(mat,unreal.MaterialExpressionLinearInterpolate,x-150,y)
L.connect_material_expressions(a,'',lp,'A'); L.connect_material_expressions(b,'',lp,'B'); L.connect_material_expressions(r,'',lp,'Alpha')
L.connect_material_property(lp,'',unreal.MaterialProperty.MP_BASE_COLOR)
rg=L.create_material_expression(mat,unreal.MaterialExpressionScalarParameter,x-150,y+250)
rg.set_editor_property('parameter_name','Roughness'); rg.set_editor_property('default_value',0.9)
L.connect_material_property(rg,'',unreal.MaterialProperty.MP_ROUGHNESS)
L.delete_material_expression(mat,old)
L.recompile_material(mat)
print('SAVED',unreal.EditorAssetLibrary.save_asset('/Game/Materials/M_GrassWind',only_if_is_dirty=False))
f=unreal.load_asset('/Game/Materials/M_Foliage')
c=L.get_material_property_input_node(f,unreal.MaterialProperty.MP_BASE_COLOR)
c.set_editor_property('constant',unreal.LinearColor(0.10,0.13,0.05,1))
L.recompile_material(f); print('SAVEDF',unreal.EditorAssetLibrary.save_asset('/Game/Materials/M_Foliage',only_if_is_dirty=False))
