import unreal
at=unreal.AssetToolsHelpers.get_asset_tools(); eal=unreal.EditorAssetLibrary; mel=unreal.MaterialEditingLibrary
sms=unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
SRC='E:/game-dev-team/assets/izba_slate/'
DEST='/Game/Environment/Buildings'
tt=unreal.AssetImportTask()
for k,v in [('filename',SRC+'T_IzbaSlate_D.png'),('destination_path',DEST),('destination_name','T_IzbaSlate_D'),('replace_existing',True),('automated',True),('save',False)]: tt.set_editor_property(k,v)
at.import_asset_tasks([tt])
tex=unreal.load_asset(DEST+'/T_IzbaSlate_D')
print('TEX',tex.get_path_name(),tex.blueprint_get_size_x(),tex.blueprint_get_size_y(),'srgb',tex.get_editor_property('srgb'))
mp=DEST+'/M_IzbaSlate'
if eal.does_asset_exist(mp): mat=unreal.load_asset(mp)
else:
    mat=at.create_asset('M_IzbaSlate',DEST,unreal.Material,unreal.MaterialFactoryNew())
    ts=mel.create_material_expression(mat,unreal.MaterialExpressionTextureSample,-400,0)
    ts.set_editor_property('texture',tex)
    print('CONN base',mel.connect_material_property(ts,'RGB',unreal.MaterialProperty.MP_BASE_COLOR))
    r=mel.create_material_expression(mat,unreal.MaterialExpressionConstant,-400,300); r.set_editor_property('r',0.9)
    print('CONN rough',mel.connect_material_property(r,'',unreal.MaterialProperty.MP_ROUGHNESS))
    s=mel.create_material_expression(mat,unreal.MaterialExpressionConstant,-400,400); s.set_editor_property('r',0.2)
    print('CONN spec',mel.connect_material_property(s,'',unreal.MaterialProperty.MP_SPECULAR))
    mel.recompile_material(mat)
ui=unreal.FbxImportUI()
ui.set_editor_property('import_mesh',True); ui.set_editor_property('import_as_skeletal',False); ui.set_editor_property('import_materials',False); ui.set_editor_property('import_textures',False); ui.set_editor_property('import_animations',False)
ui.set_editor_property('mesh_type_to_import',unreal.FBXImportType.FBXIT_STATIC_MESH)
d=ui.get_editor_property('static_mesh_import_data')
d.set_editor_property('combine_meshes',True); d.set_editor_property('auto_generate_collision',False); d.set_editor_property('generate_lightmap_u_vs',False); d.set_editor_property('remove_degenerates',True)
d.set_editor_property('normal_import_method',unreal.FBXNormalImportMethod.FBXNIM_IMPORT_NORMALS)
t=unreal.AssetImportTask()
for k,v in [('filename',SRC+'SM_IzbaSlate.fbx'),('destination_path',DEST),('destination_name','SM_VillageHouse'),('replace_existing',True),('automated',True),('save',False),('options',ui)]: t.set_editor_property(k,v)
at.import_asset_tasks([t])
print('IMP',list(t.get_editor_property('imported_object_paths')))
sm=unreal.load_asset(DEST+'/SM_VillageHouse')
for i in range(len(sm.get_editor_property('static_materials'))): sm.set_material(i,mat)
sm.set_editor_property('light_map_coordinate_index',1); sm.set_editor_property('light_map_resolution',256)
bs=sm.get_editor_property('body_setup'); bs.set_editor_property('collision_trace_flag',unreal.CollisionTraceFlag.CTF_USE_COMPLEX_AS_SIMPLE)
ns=sm.get_editor_property('nanite_settings'); ns.enabled=False; sm.set_editor_property('nanite_settings',ns)
sm.modify()
b=sm.get_bounding_box()
print('NEW min',b.min,'max',b.max,'tris',sm.get_num_triangles(0),'lods',sm.get_num_lods(),'uv',sms.get_num_uv_channels(sm,0))
print('NEW mats',[(str(m.material_slot_name),m.material_interface.get_path_name() if m.material_interface else None) for m in sm.get_editor_property('static_materials')])
print('NEW trace',sm.get_editor_property('body_setup').get_editor_property('collision_trace_flag'),'lm',sm.get_editor_property('light_map_coordinate_index'),sm.get_editor_property('light_map_resolution'),'nanite',sm.get_editor_property('nanite_settings').enabled)
for a in (mat,tex,sm): print('SAVE',a.get_name(),eal.save_loaded_asset(a,False))
