import unreal
les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
print('PIE', les.is_in_play_in_editor())
w = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
print('WORLD', w.get_path_name())
OUT = 'E:/game-dev-team/assets/pda_map_1010'
rt = unreal.RenderingLibrary.create_render_target2d(w, 2048, 2048, unreal.TextureRenderTargetFormat.RTF_RGBA8)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
cap = eas.spawn_actor_from_class(unreal.SceneCapture2D, unreal.Vector(5500.0, -4370.0, 30000.0), unreal.Rotator(roll=0.0, pitch=-90.0, yaw=90.0))
c = cap.capture_component2d
c.set_editor_property('projection_type', unreal.CameraProjectionMode.ORTHOGRAPHIC)
c.set_editor_property('ortho_width', 46875.0)
c.set_editor_property('texture_target', rt)
c.set_editor_property('capture_source', unreal.SceneCaptureSource.SCS_FINAL_COLOR_LDR)
c.set_editor_property('capture_every_frame', False)
pp = c.get_editor_property('post_process_settings')
pp.set_editor_property('override_vignette_intensity', True); pp.set_editor_property('vignette_intensity', 0.0)
pp.set_editor_property('override_auto_exposure_bias', True); pp.set_editor_property('auto_exposure_bias', 2.0)
c.set_editor_property('post_process_settings', pp); c.set_editor_property('post_process_blend_weight', 1.0)
c.capture_scene()
unreal.RenderingLibrary.export_render_target(w, rt, OUT, 'T_PdaMap_raw.png')
print('ROT', cap.get_actor_rotation(), 'UP', cap.get_actor_up_vector(), 'RIGHT', cap.get_actor_right_vector())
eas.destroy_actor(cap)
print('DIRTY maps', [p.get_name() for p in unreal.EditorLoadingAndSavingUtils.get_dirty_map_packages()])
